In [27]:
import numpy as np 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [61]:
def power(a):
    n= len(a)
    tol= 1e-10
    #x0 = np.ones(n)
    x0= np.array([1,1,1])
    q = x0/np.linalg.norm(x0)
    mu=0
    for i in range(10000):
        mu_old=mu
        qold=q.copy()
        znew= a@q
        q= znew/np.linalg.norm(znew)
        mu= (q.T)@a@q
        error = np.linalg.norm(q-qold)/ np.linalg.norm(q)
        #error= np.linalg.norm((q-qold)/(q))
        print(error)
        print((q-qold)/q)
        #print(np.linalg.norm(q))
        if (error<tol):
             break
        #print (mu)
    
    return mu

In [62]:

a= np.array(([4,1,2],[1,3,0],[2,0,5]))
eigenvalue= np.linalg.eig(a)
value= power(a)




print(eigenvalue)

0.2309609197047188
[ 0.11936943 -0.5411035   0.11936943]
0.11246162291133828
[ 0.00457469 -0.37712976  0.06551909]
0.05672190403888868
[-0.01406629 -0.2240281   0.03519135]
0.02924118760887351
[-0.01195295 -0.12456792  0.01860908]
0.015190313567004399
[-0.00752284 -0.06708188  0.0097681 ]
0.007909671907788266
[-0.00428098 -0.03554604  0.00511033]
0.004121462818555618
[-0.0023312  -0.01868202  0.00266917]
0.0021479898775471087
[-0.00124271 -0.00977823  0.0013929 ]
0.0011195374817485986
[-0.00065537 -0.00510729  0.00072652]
0.0005835155892756973
[-0.0003437  -0.0026648   0.00037883]
0.00030413642546314815
[-0.00017973 -0.00138967  0.0001975 ]
0.00015852035399396814
[-9.38385317e-05 -7.24504499e-04  1.02953849e-04]
8.262316162221415e-05
[-4.89546775e-05 -3.77671791e-04  5.36653746e-05]
4.306442347025853e-05
[-2.55282438e-05 -1.96860880e-04  2.79724704e-05]
2.244582023289675e-05
[-1.33091110e-05 -1.02610095e-04  1.45800466e-05]
1.1699096617349806e-05
[-6.93784971e-06 -5.34827490e-05  7.599

In [9]:
def ludecompose(a):
    a=a.astype(float)
    n= len(a)
    L= np. zeros((n,n))
    #t.tic()
    for k in range(n-1):
        p=k 
        big=abs(a[k,k])
        for i in range(k+1,n):
            if (a[i,k]>big):
                big= abs(a[i,k])
                p=i
            if (p != k):
                a[[k,p]] = a[[p,k]]
            factor= a[i,k]/a[k,k]
            L[i,k]= factor 
            for j in range (k,n):
                a[i,j] -= factor * a[k,j]

    for i in range (n):
        L[i,i] = 1
    #t.toc("Time spent in elimination is")
    u=a 
    #print(L@u)
    return L,u

In [10]:
def forwardsub(L, b):
    n = len(b)
    y = np.zeros(n)
    #t.tic()
    for i in range(n):                   
        tot = b[i]
        for j in range(i):      
            tot = tot - L[i,j] * y[j]
        y[i] = tot / L[i,i]
    #t.toc("Forward Sub time" )
    return y

In [11]:
def backsub(u,y):
    n = len(y)
    x = np.zeros(n)
    #t.tic()
    for i in range(n-1, -1, -1):
        tot = y[i]
        for j in range(i+1, n):
            tot = tot - u[i,j] * x[j]
        x[i] = tot / u[i,i]
    #t.toc()
    return x

In [12]:
def inverse(a):
    n= len(a)
    tol= 1e-10
    x0 = np.ones(n)
    q = x0/np.linalg.norm(x0)
    #print(q.T @ q)
    mu=0
    L,u = ludecompose(a)
    for i in range(100):
        
        mu_old= mu
        qold=q.copy()    
        y= forwardsub(L,q)
        znew= backsub(u, y)
        q= znew/np.linalg.norm(znew)
        print(q)
        mu= (q.T)@a@q
        error = np.linalg.norm(q-qold)/ np.linalg.norm(q)
        if (error<tol):
             break
        print (mu)
    return mu

In [15]:
inverse_eigen= inverse(a)
eigenvalue= np.linalg.eig(a)


print(eigenvalue)

[0.26148818 0.84983659 0.45760432]
4.41025641025641
[-0.21177618  0.91018698  0.35596421]
2.611219393348763
[-0.48524335  0.80356654  0.34470234]
2.0241917948326345
[-0.59601898  0.71232622  0.3706113 ]
1.8972587284254647
[-0.64096179  0.65806591  0.39511675]
1.8664573484088987
[-0.66060417  0.62811078  0.41119214]
1.858149647084685
[-0.66982816  0.6119143   0.42058427]
1.8558204134807565
[-0.67439236  0.60322051  0.42581682]
1.8551599398235408
[-0.67672682  0.59856791  0.42866917]
1.8549720774405412
[-0.67794409  0.59608147  0.43020772]
1.8549185983772785
[-0.67858567  0.59475359  0.43103324]
1.8549033710556297
[-0.67892578  0.5940447   0.43147501]
1.8548990350615937
[-0.67910664  0.59366633  0.43171108]
1.8548978003640988
[-0.67920298  0.59346439  0.43183716]
1.8548974487759426
[-0.67925434  0.59335662  0.43190446]
1.8548973486588152
[-0.67928173  0.59329912  0.43194038]
1.854897320149772
[-0.67929634  0.59326843  0.43195955]
1.854897312031624
[-0.67930414  0.59325205  0.43196978]
1.

array([4, 1, 2])

In [13]:

a= np.array(([4,1,2],[1,3,0],[2,0,5]))
n=len(a)

a = a.astype(float)

q= col0/np.linalg.norm(col0)
print(q)
print((q.T@a[:,0]))
for i in range (1,n):
    print(a[:,i])
    a[:,i] = a[:,i] - (q.T)@a[:,i]*q
    print(a[:,i])
    q = a[:,i] / np.linalg.norm(a[:,i])
    print(q)
    
    

[0.87287156 0.21821789 0.43643578]
4.582575694955841
[1. 3. 0.]
[-0.33333333  2.66666667 -0.66666667]
[-0.12038585  0.96308682 -0.24077171]
[2. 0. 5.]
[1.82608696 1.39130435 4.65217391]
[0.35199788 0.26818886 0.8967565 ]


In [22]:
import numpy as np

# Initial matrix
A = np.array([[4, 1, 2],
              [1, 3, 0],
              [2, 0, 5]], dtype=float)

# Save an untouched copy of the original matrix for Rayleigh quotient
a_orig = A.copy()

n = len(A)
iterations = 50

# Track eigenvectors: starts as identity matrix I
eigenvectors = np.eye(n)

for step in range(iterations):
    Q = np.zeros((n, n))
    R = np.zeros((n, n))
    
    for j in range(n):
        v = A[:, j].copy()
        for i in range(j):
            R[i, j] = Q[:, i].T @ A[:, j]
            v = v - R[i, j] * Q[:, i]
            
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
        
    # --- STEP 2: Update A = R @ Q ---
    A = R @ Q
    
    # Accumulate Q matrices to get the eigenvectors
    eigenvectors = eigenvectors @ Q

# Initialize array to store eigenvalues
eigenvalues = np.zeros(n)

# Rayleigh quotient using the original matrix and coplt.figure()
for vector in vectors:
    plt.quiver(0, 0, vector[0], vector[1], angles='xy', scale_units='xy', scale=1, color='darkmagenta')

plt.xlim(-2, 5)
plt.ylim(-2, 5)
plt.title('Multiple 2D Vectors')
plt.grid(True)
plt.show()
mputed eigenvectors
for k in range(n):
    qk = eigenvectors[:, k]
    eigenvalues[k] = (qk.T @ A @ qk) / (qk.T @ qk)

print("Converged A matrix (diagonalized):\n", np.round(A, 4))
print("\nComputed Eigenvalues via Rayleigh quotient:\n", eigenvalues)
print("\nComputed Eigenvectors (columns):\n", eigenvectors)

# Verification using numpy's built-in solver
true_vals, true_vecs = np.linalg.eigh(a_orig)
print("\nNumPy exact eigenvalues for check:\n", true_vals)


print(np.linalg.eigh(A))

Converged A matrix (diagonalized):
 [[ 6.6691 -0.      0.    ]
 [-0.      3.476  -0.    ]
 [ 0.     -0.      1.8549]]

Computed Eigenvalues via Rayleigh quotient:
 [3.82077842 3.53222582 4.64699576]

Computed Eigenvectors (columns):
 [[ 0.63117897  0.37436195 -0.67931306]
 [ 0.17202654  0.7864357   0.59323331]
 [ 0.75632002 -0.49129626  0.43198148]]

NumPy exact eigenvalues for check:
 [1.85489731 3.4760236  6.66907909]
EighResult(eigenvalues=array([1.85489731, 3.4760236 , 6.66907909]), eigenvectors=array([[-1.75637649e-28,  4.20708840e-15, -1.00000000e+00],
       [ 2.61659224e-14,  1.00000000e+00,  4.20708840e-15],
       [ 1.00000000e+00, -2.61659224e-14, -2.85719998e-28]]))
